# Generated by Django 4.2.2 on 2023-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='GL_account', max_length=100),
        ),
    ]
