# Generated by Django 4.2.2 on 2023-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0005_alter_transaction_account1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='asset', max_length=100),
        ),
    ]
