# Generated by Django 4.2.2 on 2023-06-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0006_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
