# Generated by Django 4.2.2 on 2023-06-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_account', models.CharField(default='service revenue', max_length=100)),
                ('debit_account', models.CharField(default='utility expense', max_length=100)),
                ('account_type', models.CharField(default='GL_account', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.IntegerField()),
                ('debit_amount', models.IntegerField()),
                ('date', models.DateField()),
                ('account1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='statements.account')),
                ('account2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit', to='statements.account')),
            ],
        ),
    ]
